// Fallback data served before the first save from the admin dashboard.
// After that, the live copy lives in Vercel Blob (data/config-*.json).
export default {
  tracks: [
    { title: 'ANCIENT WORDS',     slot: 'OPENING', audioUrl: null, filename: '' },
    { title: 'BEN ZAYIFKEN',      slot: 'HYMN',    audioUrl: null, filename: '' },
    { title: 'JESUS HEALS',       slot: 'WORSHIP', audioUrl: null, filename: '' },
    { title: 'OCEANS',            slot: 'WORSHIP', audioUrl: null, filename: '' },
    { title: 'PEACE',             slot: 'WORSHIP', audioUrl: null, filename: '' },
    { title: 'YÜCEDİR KRALIMIZ',  slot: 'CLOSING', audioUrl: null, filename: '' },
    { title: 'TRACK 07', slot: '---', audioUrl: null, filename: '' },
    { title: 'TRACK 08', slot: '---', audioUrl: null, filename: '' },
    { title: 'TRACK 09', slot: '---', audioUrl: null, filename: '' },
    { title: 'TRACK 10', slot: '---', audioUrl: null, filename: '' },
    { title: 'TRACK 11', slot: '---', audioUrl: null, filename: '' },
    { title: 'TRACK 12', slot: '---', audioUrl: null, filename: '' },
    { title: 'TRACK 13', slot: '---', audioUrl: null, filename: '' },
    { title: 'TRACK 14', slot: '---', audioUrl: null, filename: '' },
    { title: 'TRACK 15', slot: '---', audioUrl: null, filename: '' },
    { title: 'TRACK 16', slot: '---', audioUrl: null, filename: '' },
    { title: 'TRACK 17', slot: '---', audioUrl: null, filename: '' },
    { title: 'TRACK 18', slot: '---', audioUrl: null, filename: '' },
    { title: 'TRACK 19', slot: '---', audioUrl: null, filename: '' },
    { title: 'TRACK 20', slot: '---', audioUrl: null, filename: '' },
  ],
  program: [
    ['13:00', 'OPENING', true],
    ['13:10', 'SABBATH SCHOOL', false],
    ['14:10', 'BREAK 15 MINUTES', false],
    ['14:25', 'WELCOME', false],
    ['14:30', 'HYMN', true],
    ['14:45', 'MESSAGE', false],
    ['15:30', 'WORSHIP', true],
    ['15:45', 'GIFTS / PRAYER', false],
    ['16:00', 'WORSHIP', true],
    ['16:30', 'WORSHIP', true],
    ['16:50', 'CLOSING', true],
    ['17:00', 'LUNCH TOGETHER', false],
  ],
};
